site_name: Ejercicio 1 Prueba Capgemini
nav:
- Home: index.md
- Instalación de dependencias y Uso: instalacion-y-uso
- Analisis exploratorio: analisis-exploratorio.ipynb
- Transformacion y seleccion de modelo: transformacion-seleccion-modelo.ipynb

plugins:
  - mkdocs-jupyter