site_name: Ejercicio 2 Prueba Capgemini
nav:
- Home: index.md
- Instalación de dependencias y Uso: instalacion-y-uso
- Analisis exploratorio: analisis-exploratorio.ipynb
- Seleccion del modelo: seleccion-modelo.ipynb

plugins:
  - mkdocs-jupyter